blank_issues_enabled: false
contact_links:
  - name: General questions or discussion
    url: https://github.com/JasonY199/game_nights/discussions
    about: Use Discussions for open-ended feedback or conversation
